apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.config.flaskEnv}}-maria-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: 1234Root
  MYSQL_DATABASE: My_maria
  MYSQL_USER: maria
  MYSQL_PASSWORD: AppSecrets


