apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-flask-{{.Values.config.flaskEnv}}
spec:
  podSelector:
    matchLabels:
      app: {{.Values.config.flaskEnv}}
  ingress:
    - ports:
        - protocol: TCP
          port: 5000
  policyTypes:
    - Ingress
