apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-maria-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{.Values.mariadb.rootPassword}}
  MYSQL_DATABASE: {{.Values.mariadb.database}}
  MYSQL_USER: {{.Values.mariadb.username}}
  MYSQL_PASSWORD: {{.Values.mariadb.password}}
