apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flask-cert
spec:
  secretName: flask-cert-secret
  commonName: flask.local
  dnsNames:
    - flask.local
  issuerRef:
    name: selfsigned
    kind: Issuer
