apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaskblog
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/Abdulrahman-122/Blog_bost_with_ArgoCd    
    targetRevision: HEAD
    path: Project1/Project1_metrics_logs_traces_Argocd/flask-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc  # this is the name of the cluster (dns name)  
    namespace: my-ns
  syncPolicy:  # what it will do when source,deestination differ.
    automated:    #automatically apply git changes
      prune: true  # delete the actual state in order to get to the desired state
      selfHeal: true   # in order if you make changing at kubernetes rather than git  this command will recouncil your git with  your kubernetes.

