apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaskblog
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Abdulrahman-122/Blog_bost_with_ArgoCd    
    targetRevision: HEAD
    path: Project1/Project1_metrics_logs_traces_Argocd/flask-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: my-ns
  syncPolicy:  # in order to make desired state like the actual state
    automated:  #apply automatically
      prune: true  # this will apply the changing on the cluster so that if some resources  need to be removed it will removed it.
      selfHeal: true     # don't run  outofsync and stop start sync even if the desired state not like the actual state.



