---
# Source: flask-app/templates/networkpolicy/allow_flask.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-flask
spec:
  podSelector:
    matchLabels:
      app: production
  ingress:
    - ports:
        - protocol: TCP
          port: 5000
  policyTypes:
    - Ingress

---
# Source: flask-app/templates/networkpolicy/allow_maria.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: maria-policy
spec:
  podSelector:
    matchLabels:
      app: mariadb
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: production
      ports:
        - protocol: TCP
          port: 3306
  policyTypes:
    - Ingress

---
# Source: flask-app/templates/back_front_kube/secretkey.yaml
apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
stringData:
  SECRET_KEY: "de9ddae3cb37eec8b80727c3ec7eb192aad9bd265404e4015c0593dfadd45c85"
  DATABASE_URL: "mysql+pymysql://maria:AppSecrets@production-mariadb-0.production-mariadb-headless/My_maria"
#you may write dns name as headless-service instead of podname-headless but here as we have just one pod so is good.

---
# Source: flask-app/templates/database_kube/secret-maria.yaml
apiVersion: v1
kind: Secret
metadata:
  name: production-maria-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: 1234Root
  MYSQL_DATABASE: My_maria
  MYSQL_USER: maria
  MYSQL_PASSWORD: AppSecrets

---
# Source: flask-app/templates/back_front_kube/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
data:
  FLASK_APP: "run.py"
  FLASK_DEBUG: "production"


---
# Source: flask-app/templates/back_front_kube/pvc-pictures.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profile-pictures-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 500Mi
  
      #later with aws 
  #storageClassName: efs-sc


---
# Source: flask-app/templates/back_front_kube/Flask_service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: ClusterIP
  selector:
    app: production
  ports:
    - port: 5000  #this is the port that the other internal service will call this service.
      targetPort: 5000
      # nodePort: 30008 unhash in case you didn't use loadbalancer like traefik but in case you used it okay hash it.


---
# Source: flask-app/templates/database_kube/with_headless/headless_service.yaml
apiVersion: v1
kind: Service
metadata:
  name: production-mariadb-headless
  labels:
    app: mariadb
spec:
    ports:
      - port: 3306
        name: mysql
    clusterIP: None
    selector:
      app: mariadb

---
# Source: flask-app/templates/back_front_kube/Flask_deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: production

  template:
    metadata:
      labels:
        app: production
    spec:
      securityContext:
       runAsUser: 1000
       runAsGroup: 1000
       fsGroup: 1000   #this ensure that the gp2(volume) can be ran by the user as it by default runs as root
      containers:
        - name: flask
         # image: abdulrahmanqasim/flaskblog-multiplats:v1 
          image: abdulrahmanqasim/flaskblog:v2
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
          
              memory: 512Mi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                -  ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: profile-storage
              mountPath: /app/flaskblog/static/profile_pics
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: SECRET_KEY

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: DATABASE_URL
                              

            - name: FLASK_APP
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: FLASK_APP
      volumes:
        - name: profile-storage
          persistentVolumeClaim:
            claimName: profile-pictures-pvc



---
# Source: flask-app/templates/back_front_kube/flask-hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  production
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80   #now -> each second (metrics server will do the following
      # look at cpu of the pods -> find their average then divide it by the max limit of the cpu  which is 500m  -> averageof pods/500 -> resule is a percentage if it exceeds 80 -> server will make scale up -> if not -> it will make scale down okay (make sure metrics server is running on kube-system.


---
# Source: flask-app/templates/database_kube/with_headless/statefule_maria.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: production-mariadb
spec:
  serviceName: production-mariadb-headless
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:12
          ports: 
            - containerPort: 3306
          volumeMounts:
            - name: maria-volume-mount
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: production-maria-secret
                  key:  MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: production-maria-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: production-maria-secret
                  key:  MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: production-maria-secret
                  key: MYSQL_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: maria-volume-mount
      spec:
        storageClassName: gp2
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
            #notice: we didn't make any pvc it will be automatically for each pod you will generate by replicas.



---
# Source: flask-app/templates/aws_ingress.yaml
apiVersion:  networking.k8s.io/v1
kind: Ingress
metadata:
  name: aws-flask-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb

  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-service
                port:
                  number: 5000


