deploymentMode: SingleBinary
singleBinary:
  replicas: 1
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb                 #timeseries database 
        object_store: filesystem    #default storage class of kubernetes
        schema: v13                 # this is the version of Loki
        index:
          prefix: index_              # use index for every log
          period: 24h                #that means rest of the index will change every 24 h.
chunkCache:           #disable all of these production  capabilities for now we just  need single binary which 1 replica contain most of these capabilities
  enabled: false

resultsCache:
  enabled: false
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
gateway:
  enabled: false
ingestor:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0


