apiVersion: v1
kind: Secret
metadata:
  name: electro-secret
  namespace: my-ns1
type: Opaque
stringData:
  DB_USER: "electro"
  DB_PASSWORD: "electro_user_pass"
  DB_ROOT_PASSWORD: "electro_root_pass"
  JWT_KEY: +wmvyl8MmMTLhdgr1EzdHAfOoXTqd7hSmLFQN5tSwVnMVUzPz4OAg4Sim45aQUk1N5Rhqh1UIXyCl97FXtXQRA==
  CONNECTION_STRING: "Server=mariadb;Port=3306;Database=electro_db;User=electro;Password=electro_user_pass;SslMode=None;"

