apiVersion: v1
kind: Service
metadata:
  name: flask-service-{{.Values.config.flaskEnv}}
  labels:
    app: {{.Values.config.flaskEnv}}

spec:
  type: ClusterIP
  selector:
    app: {{.Values.config.flaskEnv}}
  ports:
    - name: http
      port: 5000  #this is the port that the other internal service will call this service.
      targetPort: 5000
      # nodePort: 30008 unhash in case you didn't use loadbalancer like traefik but in case you used it okay hash it.


