apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profile-pictures-pvc-{{.Values.config.flaskEnv}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 500Mi
  
      #later with aws 
  #storageClassName: efs-sc


