apiVersion: v1
kind: Secret
metadata:
  name: flask-secret-{{.Values.config.flaskEnv}}
type: Opaque
stringData:
  SECRET_KEY: "de9ddae3cb37eec8b80727c3ec7eb192aad9bd265404e4015c0593dfadd45c85"
  DATABASE_URL: "mysql+pymysql://maria:AppSecrets@{{.Values.config.flaskEnv}}-mariadb-0.{{.Values.config.flaskEnv}}-mariadb-headless/My_maria"
#you may write dns name as headless-service instead of podname-headless but here as we have just one pod so is good.
