apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  {{.Release.Name}}
  minReplicas: {{.Values.hpa.minReplicas}}
  maxReplicas: {{.Values.hpa.maxReplicas}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{.Values.hpa.cpuUtil}}   #now -> each second (metrics server will do the following
      # look at cpu of the pods -> find their average then divide it by the max limit of the cpu  which is 500m  -> averageof pods/500 -> resule is a percentage if it exceeds 80 -> server will make scale up -> if not -> it will make scale down okay (make sure metrics server is running on kube-system.

