apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.storage.claimname}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.storage.size}}
  
      #later with aws 
  #storageClassName: efs-sc

