apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.secret.name}}
type: Opaque
stringData:
  SECRET_KEY: "de9ddae3cb37eec8b80727c3ec7eb192aad9bd265404e4015c0593dfadd45c85"
  DATABASE_URL: "mysql+pymysql://{{ .Values.mariadb.username }}:{{ .Values.mariadb.password }}@{{ .Release.Name }}-mariadb-0.{{ .Release.Name }}-mariadb-headless/{{ .Values.mariadb.database }}"
#you may write dns name as headless-service instead of podname-headless but here as we have just one pod so is good.
