services:
  flask:
    build: .
    container_name: backend_flask
    ports:
      - "8001:5000"
    environment:
      DATABASE_URL: mysql+pymysql://maria:AppSecrets@mariadb/My_maria
      FLASK_APP: run.py
      SECRET_KEY: "de9ddae3cb37eec8b80727c3ec7eb192aad9bd265404e4015c0593dfadd45c85"
    healthcheck:
      test: ["CMD","curl","-f","http://127.0.0.1/5000/"]
      interval: 20s
      timeout: 10s
      retries: 5
    depends_on:
      mariadb:
         condition: service_healthy
 
  mariadb:
    image: mariadb:latest
    healthcheck:
      test: ["CMD","mariadb-admin","ping","-h","127.0.0.1","-u","root","-p1234Root"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: database_maria
    environment:
      MYSQL_ROOT_PASSWORD: 1234Root
      MYSQL_DATABASE: My_maria
      MYSQL_USER: maria
      MYSQL_PASSWORD: AppSecrets
    volumes:
      - maria_data:/var/lib/mysql
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  Grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

    depends_on:
      - prometheus


volumes:
  maria_data:
  grafana_data:


